name: Create Tags on Merge

on:
  push:
    branches:
      - 'feat/*'
      - 'fix/*'

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract version from branch name
        id: extract-version
        run: echo "::set-output name=version::$(echo ${GITHUB_REF#refs/heads/} | cut -d '/' -f 2)"

      - name: Create tag
        id: create-tag
        if: startsWith(github.ref, 'refs/heads/feat/') || startsWith(github.ref, 'refs/heads/fix/')
        run: git tag -a "v${{ steps.extract-version.outputs.version }}" -m "Version ${{ steps.extract-version.outputs.version }}"

      - name: Push tag to GitHub
        if: steps.create-tag.outputs.version
        uses: mathieudutour/github-tag-action@v5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tags: "v${{ steps.extract-version.outputs.version }}"
